### ISSUE TITLE
Bug: Shopping List Duplicates Itself

### ISSUE THREAD

**Issue by avaziri** [Ilysen/ShoppingList#1]
At some point in my playthrough I started to get an errors where there seemed to be two shopping lists with different contents. They would display one after another whenever I activated the shopping list.

Over time it has gotten exponentially worse. Now I have dozens of shopping lists. Since the problem started slowly, I am not sure what the proximal cause was. Perhaps the shopping list does not play well with the golem? Just a guess since they have different action menus and I feel this only started happening late in the playthrough.

![Screenshot 2024-03-04 000943](https://github.com/Ilysen/ShoppingList/assets/3925736/11c0c0fa-8b5f-4778-af1d-9c6c01fc2483)

**Comment by Ilysen** [comment]
hhhuh, that's odd. what other mods are you running, if any, and what game and mod version are you playing on? if you can attach your `Player.log`, that'd be a big help too

**Comment by Ilysen** [comment]
cannot repro without further information like OS and ideally a player.log upload -- if you have more info, leave it here in a comment and I can reopen this, but otherwise this isn't super actionable on my part

**Comment by Ilysen** [comment]
have received another report of the same issue, this time with a bunch of identifying info that helped me pin it down, and been participating in extensive debugging with it; it seems to be exclusive to Linux, which is the reason I wasn't able to repro it. working on a fix that should hopefully be up shortly

**Comment by Ilysen** [comment]
should be fixed in 1.0.2
